# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7646, 0.2626, 0.0415],
        [0.5901, 0.4462, 0.4753],
        [0.0491, 0.7393, 0.8340],
        [0.3449, 0.0484, 0.1658],
        [0.7103, 0.9375, 0.8593]])


In [2]:
torch.__version__

'2.2.2'

## Introduction to tensors

### Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# return actual value
scalar.item() # only works on single element

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
# random, zero, one tensors (similar to numpy)
random_tensor = torch.rand(size = (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7367, 0.3029, 0.5709, 0.4444],
         [0.9956, 0.3080, 0.6302, 0.3476],
         [0.2071, 0.4468, 0.8179, 0.7336]]),
 torch.float32)

In [20]:
# create image-like random tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # 3 channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
# zeros tensor
zeros = torch.zeros(size = (3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# ones tensor
ones = torch.ones(size = (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
# can use arange() similarly to numpy
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# can copy the size/shape of a tensor into a zeros tensor...
ten_zeros = torch.zeros_like(input = zero_to_ten, dtype = torch.float32)
ten_zeros, ten_zeros.dtype

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), torch.float32)

In [32]:
# info about tensor
some_tensor = torch.rand(3, 4)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [33]:
# operations
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [34]:
# alternatives - more common to use * + -
print(torch.multiply(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


In [35]:
# element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [36]:
# matrix multiplication (obvi needs to be valid)
tensor.matmul(tensor)
# this is (1 x 3) * (1 x 3) but it seems to work anyway? weird

tensor(14)

In [38]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
# can use transpose
torch.matmul(tensor_A, tensor_B.T)

# also can use...
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [41]:
# max (or min)
tensor.max(), torch.max(tensor)

(tensor(3), tensor(3))

In [42]:
# mean
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [44]:
# change dtype to use mean()
tensor = tensor.type(torch.float32)
tensor.mean()

tensor(2.)

In [45]:
# example of matmul with linear layer
x = tensor_A # 3 x 2

torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 2, # inner dimension of input (2)
                out_features = 6)

output = linear(x)

output, output.shape

(tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]))

In [50]:
# reshape
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [51]:
x.reshape(1, 5)

RuntimeError: shape '[1, 5]' is invalid for input of size 7

In [52]:
x_reshaped = x.reshape(1, 7) # adding a dimension
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
# view - keeps same data as original, change in view changes original
z = x.view(1, 7)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [64]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [70]:
# squeeze
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7.])

In [74]:
# unsqueeze (add dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [75]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [77]:
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))